version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - JWT_SECRET=your_jwt_secret
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/type_messenger
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - PORT=3000

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: type_messenger
    ports:
      - '5432:5432'
